[project]
name = "fullsite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.6",
    "django-environ>=0.12.0",
    "django-extensions>=4.1",
    "django-storages[s3]>=1.14.6",
    "pre-commit>=4.3.0",
    "werkzeug>=3.1.3",
    "whitenoise>=6.11.0",
]

[tool.djlint]
profile="django"
