[project]
name = "fullsite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.6",
    "django-anymail[mailgun]>=13.1",
    "django-environ>=0.12.0",
    "django-extensions>=4.1",
    "django-storages[s3]>=1.14.6",
    "pre-commit>=4.3.0",
    "social-auth-app-django>=5.5.1",
    "werkzeug>=3.1.3",
    "whitenoise>=6.11.0",
    "coverage>=7.6",
    "pytest>=8.3",
    "pytest-cov>=5.0",
    "pytest-django>=4.9",
    "pytest-xdist>=3.6",
    "django-tasks>=0.8.1",
]

[tool.djlint]
profile="django"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = "tests.py test_*.py *_tests.py"
addopts = "--cov=accounts --cov=homepage --cov=config --cov=points --cov-report=term-missing --cov-fail-under=100"

[tool.coverage.run]
omit = [
    "manage.py",
    "*/migrations/*",
    "*/admin.py",
]
